version: "2"
services:
    db:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    frontend:
        build:
            context: ./frontend/
            dockerfile: dev.dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
    
    imageit:
        image: cthit/imageit
        environment:
            IMAGEIT_POSTGRES_USER: imageit
            IMAGEIT_POSTGRES_PASSWORD: password
            IMAGEIT_POSTGRES_DB: imageit
            IMAGEIT_POSTGRES_HOST: imageit_db
        ports: 
            - 5000:5000
        command: sh startscript.sh

    imageit_db:
        image: postgres:11
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: imageit
            POSTGRES_DB: imageit
#    gamma_backend:
#        build:
#            context: ./backend
#            dockerfile: dev.Dockerfile
#        ports:
#            - 8081:8081
