version: "2"
services:
  db: 
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: user   # These should all be changed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend/
      dockerfile: dockerfile
    ports: 
      - 9090:9090
    environment:
      COOKIE_DOMAIN: http://localhost
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      
  redis:
    image: redis
    ports:
      - 6379:6379
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
