spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none


  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate: INFO

security:
  jwt:
    token:
      secret-key: xJqKgDuIikgjkvOXI71j8LKkBlKg3bdr7/WYN6Q0uDs= # This is only for Development, should also be a secret one for Production
      expire-length: 2592000000 #One Month. Subject to change.
      issuer: http://localhost:8081

application:
  frontend-client-details:
    client-id: ${FRONTEND_CLIENT_ID:7hAdUEtMo4MgFnA7ZoZ41ohTe1NNRoJmjL67Gf0NIrrBnauyhc}
    client-secret: ${FRONTEND_CLIENT_SECRET:LBoxmzohQOSRCz99uBhS0IjLglxUOaLRXJxIC8iWuHTWYCLLqo}
    redirect-uri: ${FRONTEND_REDIRECT_URI:http://localhost:3000/login}
    successful-login-uri: ${SUCCESSFUL_LOGIN:http://localhost:3000}
  standard-admin-account:
    password: ${ADMIN_PASSWORD:password}
  gotify:
    key: "key"                  # This is not needed, but application crashes since it looks for these values.
    url: "gotify.chalmers.it"
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
  auth:
    accessTokenValidityTime: 3600
    autoApprove: true
    refreshTokenValidityTime: 500000000
  imageit:
    url: ${IMAGEIT_URL:http://localhost:5000}
    apiKey: ${IMAGEIT_API_KEY:secret}
